name: cameo_env
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _py-xgboost-mutex
  - _r-mutex
  - abseil-cpp
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow-cpp
  - asttokens
  - async-lru
  - aws-c-common
  - aws-c-event-stream
  - aws-checksums
  - aws-sdk-cpp
  - babel
  - backcall
  - beautifulsoup4
  - binutils_impl_linux-64
  - binutils_linux-64
  - blas
  - bleach
  - boost-cpp
  - bottleneck
  - brotli
  - brotli-bin
  - brotli-python
  - bwidget
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - charset-normalizer
  - cloudpickle
  - cmdstan
  - cmdstanpy
  - colorama
  - comm
  - contourpy
  - convertdate
  - cuda-cudart
  - cuda-cupti
  - cuda-libraries
  - cuda-nvrtc
  - cuda-nvtx
  - cuda-runtime
  - cuda-version
  - cudatoolkit
  - cudnn
  - curl
  - cycler
  - cyrus-sasl
  - cython
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - ephem
  - exceptiongroup
  - executing
  - expat
  - ffmpeg
  - fontconfig
  - fonttools
  - freetype
  - fribidi
  - fsspec
  - future
  - gcc_impl_linux-64
  - gcc_linux-64
  - gflags
  - gfortran_impl_linux-64
  - gfortran_linux-64
  - giflib
  - glib
  - glog
  - gmp
  - gnutls
  - graphite2
  - grpc-cpp
  - gst-plugins-base
  - gstreamer
  - gxx_impl_linux-64
  - gxx_linux-64
  - h11
  - harfbuzz
  - holidays
  - httpcore
  - httpx
  - icu
  - idna
  - importlib-metadata
  - importlib-resources
  - importlib_metadata
  - importlib_resources
  - intel-openmp
  - ipykernel
  - ipython
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter
  - jupyter-lsp
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kernel-headers_linux-64
  - keyutils
  - kiwisolver
  - krb5
  - lame
  - lapack
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libblas
  - libboost
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libclang
  - libclang13
  - libcublas
  - libcufft
  - libcufile
  - libcups
  - libcurand
  - libcurl
  - libcusolver
  - libcusparse
  - libdeflate
  - libedit
  - libev
  - libevent
  - libexpat
  - libffi
  - libgcc-devel_linux-64
  - libgcc-ng
  - libgfortran
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - libiconv
  - liblapack
  - libllvm14
  - libnghttp2
  - libnpp
  - libnsl
  - libnvjpeg
  - libopenblas
  - libpng
  - libpq
  - libprotobuf
  - libsodium
  - libsqlite
  - libssh2
  - libstdcxx-devel_linux-64
  - libstdcxx-ng
  - libthrift
  - libtiff
  - libuuid
  - libwebp
  - libwebp-base
  - libxcb
  - libxgboost
  - libxkbcommon
  - libxml2
  - libxslt
  - libzlib
  - lightning-utilities
  - llvmlite
  - lunarcalendar
  - lz4-c
  - magma
  - make
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mkl
  - munkres
  - mysql
  - nbclient
  - nbconvert
  - nbformat
  - nccl
  - ncurses
  - nest-asyncio
  - nettle
  - nfoursid
  - ninja
  - nlopt
  - notebook
  - notebook-shim
  - nspr
  - nss
  - numba
  - numexpr
  - numpy
  - numpy-base
  - openblas
  - openh264
  - openjpeg
  - openssl
  - orc
  - overrides
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - pango
  - parso
  - patsy
  - pcre
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - platformdirs
  - plotly
  - ply
  - pmdarima
  - prometheus_client
  - prompt_toolkit
  - prophet
  - protobuf
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - py-xgboost
  - pyarrow
  - pycparser
  - pymeeus
  - pyod
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - python_abi
  - pytorch
  - pytorch-cuda
  - pytorch-lightning
  - pytorch-mutex
  - pytz
  - pyyaml
  - pyzmq
  - qt-main
  - qt-webengine
  - qtconsole
  - qtpy
  - qtwebkit
  - r-anytime
  - r-askpass
  - r-assertthat
  - r-backports
  - r-base
  - r-base64enc
  - r-bit
  - r-bit64
  - r-blob
  - r-broom
  - r-bslib
  - r-cachem
  - r-callr
  - r-cellranger
  - r-cli
  - r-clipr
  - r-colorspace
  - r-conflicted
  - r-cpp11
  - r-crayon
  - r-curl
  - r-data.table
  - r-dbi
  - r-dbplyr
  - r-digest
  - r-dplyr
  - r-dtplyr
  - r-ellipsis
  - r-evaluate
  - r-fansi
  - r-farver
  - r-fastmap
  - r-fontawesome
  - r-forcats
  - r-forecast
  - r-fracdiff
  - r-fs
  - r-gargle
  - r-generics
  - r-ggplot2
  - r-glue
  - r-googledrive
  - r-googlesheets4
  - r-gtable
  - r-haven
  - r-highr
  - r-hms
  - r-htmltools
  - r-htmlwidgets
  - r-httr
  - r-ids
  - r-isoband
  - r-jquerylib
  - r-jsonlite
  - r-knitr
  - r-labeling
  - r-lattice
  - r-lifecycle
  - r-lmtest
  - r-lubridate
  - r-magrittr
  - r-mass
  - r-matrix
  - r-memoise
  - r-mgcv
  - r-mime
  - r-modelr
  - r-munsell
  - r-nlme
  - r-nloptr
  - r-nnet
  - r-openssl
  - r-pillar
  - r-pkgconfig
  - r-prettyunits
  - r-processx
  - r-progress
  - r-ps
  - r-purrr
  - r-quadprog
  - r-quantmod
  - r-r6
  - r-ragg
  - r-rappdirs
  - r-rcolorbrewer
  - r-rcpp
  - r-rcpparmadillo
  - r-readr
  - r-readxl
  - r-rematch
  - r-rematch2
  - r-reprex
  - r-rlang
  - r-rmarkdown
  - r-rstudioapi
  - r-rvest
  - r-sass
  - r-scales
  - r-selectr
  - r-stringi
  - r-stringr
  - r-sys
  - r-systemfonts
  - r-textshaping
  - r-tibble
  - r-tidyr
  - r-tidyselect
  - r-tidyverse
  - r-timechange
  - r-timedate
  - r-tinytex
  - r-tseries
  - r-tsibble
  - r-ttr
  - r-tzdb
  - r-urca
  - r-utf8
  - r-uuid
  - r-vctrs
  - r-viridislite
  - r-vroom
  - r-withr
  - r-xfun
  - r-xml2
  - r-xts
  - r-yaml
  - r-zoo
  - re2
  - readline
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rpy2
  - scikit-learn
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - shap
  - simplegeneric
  - sip
  - six
  - sleef
  - slicer
  - snappy
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - stanio
  - statsforecast
  - statsmodels
  - stumpy
  - sysroot_linux-64
  - tbats
  - tbb
  - tbb-devel
  - tenacity
  - tensorboardx
  - terminado
  - threadpoolctl
  - tinycss2
  - tk
  - tktable
  - toml
  - tomli
  - torchaudio
  - torchmetrics
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - tzdata
  - tzlocal
  - u8darts
  - u8darts-torch
  - unicodedata2
  - urllib3
  - utf8proc
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - xarray
  - xgboost
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
      - amqp
      - async-timeout
      - attrs
      - billiard
      - cached-property
      - celery
      - click
      - click-didyoumean
      - click-plugins
      - click-repl
      - coloredlogs
      - cryptography
      - dill
      - filelock
      - greenlet
      - humanfriendly
      - jsonschema-specifications
      - kombu
      - maestrowf
      - markdown-it-py
      - mdurl
      - merlin
      - parse
      - prompt-toolkit
      - psutil
      - pygments
      - redis
      - referencing
      - rich
      - rpds-py
      - sqlalchemy
      - tabulate
      - typing-extensions
      - vine
      - wcwidth
